// Generated by scripts/build-sw.mjs. Do not edit by hand.
const CACHE = "iggym-e0f9246f3fa8";
const PRECACHE = [
  "/",
  "/404.html",
  "/articles/context-orchestration.html",
  "/articles/index.json",
  "/articles/token-economics.html",
  "/assets/css/fonts.css",
  "/assets/css/home.css",
  "/assets/css/site-map.css",
  "/assets/css/sites.css",
  "/assets/css/tokens.css",
  "/assets/css/tool.css",
  "/assets/fonts/dm-mono-normal-400.woff2",
  "/assets/fonts/dm-mono-normal-500.woff2",
  "/assets/fonts/fraunces-italic-300-700.woff2",
  "/assets/fonts/fraunces-normal-300-700.woff2",
  "/assets/fonts/source-sans-3-italic-400.woff2",
  "/assets/fonts/source-sans-3-normal-400.woff2",
  "/assets/fonts/source-sans-3-normal-600.woff2",
  "/assets/img/favicon.svg",
  "/assets/img/icon-192.png",
  "/assets/img/icon-512.png",
  "/assets/img/sites/agentic-engineering.jpg",
  "/assets/img/sites/agentic-infra-weekly.jpg",
  "/assets/img/sites/ai-ops-field-notes.jpg",
  "/assets/img/sites/ai-systems-articles.jpg",
  "/assets/img/sites/apex-ai-consumer-index.jpg",
  "/assets/img/sites/applied-ai-engineering.jpg",
  "/assets/img/sites/awesome-ai-architecture.jpg",
  "/assets/img/sites/cogitatio-elegans.jpg",
  "/assets/img/sites/cognitio-viva.jpg",
  "/assets/img/sites/fde-field-notes.jpg",
  "/assets/img/sites/last-interface.jpg",
  "/assets/img/sites/one-origin.jpg",
  "/assets/img/sites/production-ai-patterns.jpg",
  "/assets/img/sites/scaling-ai-systems.jpg",
  "/assets/img/sites/sovereign-reader.jpg",
  "/assets/img/sites/systems-bench.jpg",
  "/assets/img/sites/the-ai-runbook.jpg",
  "/assets/img/sites/thumbs/agentic-engineering.jpg",
  "/assets/img/sites/thumbs/agentic-infra-weekly.jpg",
  "/assets/img/sites/thumbs/ai-ops-field-notes.jpg",
  "/assets/img/sites/thumbs/ai-systems-articles.jpg",
  "/assets/img/sites/thumbs/apex-ai-consumer-index.jpg",
  "/assets/img/sites/thumbs/applied-ai-engineering.jpg",
  "/assets/img/sites/thumbs/awesome-ai-architecture.jpg",
  "/assets/img/sites/thumbs/cogitatio-elegans.jpg",
  "/assets/img/sites/thumbs/cognitio-viva.jpg",
  "/assets/img/sites/thumbs/fde-field-notes.jpg",
  "/assets/img/sites/thumbs/last-interface.jpg",
  "/assets/img/sites/thumbs/one-origin.jpg",
  "/assets/img/sites/thumbs/production-ai-patterns.jpg",
  "/assets/img/sites/thumbs/scaling-ai-systems.jpg",
  "/assets/img/sites/thumbs/sovereign-reader.jpg",
  "/assets/img/sites/thumbs/systems-bench.jpg",
  "/assets/img/sites/thumbs/the-ai-runbook.jpg",
  "/assets/img/social-card.png",
  "/assets/img/tools/agentic-backpressure-throttle-dark.jpg",
  "/assets/img/tools/agentic-backpressure-throttle-light.jpg",
  "/assets/img/tools/ai-aggregator-dark.jpg",
  "/assets/img/tools/ai-aggregator-light.jpg",
  "/assets/img/tools/claude_context_engine_premium-dark.jpg",
  "/assets/img/tools/claude_context_engine_premium-light.jpg",
  "/assets/img/tools/context-engine-dark.jpg",
  "/assets/img/tools/context-engine-light.jpg",
  "/assets/img/tools/context-extractor-dark.jpg",
  "/assets/img/tools/context-extractor-light.jpg",
  "/assets/img/tools/context-window-optimizer-dark.jpg",
  "/assets/img/tools/context-window-optimizer-light.jpg",
  "/assets/img/tools/deterministic-agent-stateboard-dark.jpg",
  "/assets/img/tools/deterministic-agent-stateboard-light.jpg",
  "/assets/img/tools/eval-set-builder-dark.jpg",
  "/assets/img/tools/eval-set-builder-light.jpg",
  "/assets/img/tools/nanobanana-json-compiler-dark.jpg",
  "/assets/img/tools/nanobanana-json-compiler-light.jpg",
  "/assets/img/tools/prompt-matrix-evaluator-dark.jpg",
  "/assets/img/tools/prompt-matrix-evaluator-light.jpg",
  "/assets/img/tools/token-conscious-diff-stager-dark.jpg",
  "/assets/img/tools/token-conscious-diff-stager-light.jpg",
  "/assets/js/eval-checks.js",
  "/assets/js/eval-set-builder.js",
  "/assets/js/home.js",
  "/assets/js/prompt-lint.js",
  "/assets/js/prompt-tightener.js",
  "/assets/js/site-map.js",
  "/assets/js/sites.js",
  "/assets/js/sw-register.js",
  "/assets/js/theme.js",
  "/assets/js/tool-kit.js",
  "/feed.xml",
  "/index.html",
  "/manifest.webmanifest",
  "/sitemap.xml",
  "/sites/index.html",
  "/tools/agentic-backpressure-throttle.html",
  "/tools/ai-aggregator.html",
  "/tools/claude_context_engine_premium.html",
  "/tools/context-engine.html",
  "/tools/context-extractor.html",
  "/tools/context-window-optimizer.html",
  "/tools/deterministic-agent-stateboard.html",
  "/tools/eval-set-builder.html",
  "/tools/index.json",
  "/tools/nanobanana-json-compiler.html",
  "/tools/prompt-matrix-evaluator.html",
  "/tools/token-conscious-diff-stager.html"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((n) => n.startsWith("iggym-") && n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  // Only same-origin requests. Outside services (AI providers, the Worker, analytics) always go to the network.
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).catch(() => {
        // Offline and not cached: show the 404 page for navigations, otherwise fail.
        if (req.mode === "navigate") return caches.match("/404.html", { ignoreSearch: true });
        return Response.error();
      });
    })
  );
});
