// Writes sw.js: a service worker that precaches every page and asset in the site.
// The cache name is a hash of the precached files, so any content change installs a fresh cache.
// Run from the repo root after any change: node scripts/build-sw.mjs
// Check only (fails if sw.js is stale): node scripts/build-sw.mjs --check
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKIP = new Set(['.git', 'node_modules', 'tests', 'tasks', 'scripts', 'resume']);
const INCLUDE = new Set(['.html', '.css', '.js', '.woff2', '.jpg', '.png', '.svg', '.webp', '.webmanifest', '.xml', '.json']);

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP.has(name) || name.startsWith('.')) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (INCLUDE.has(extname(p)) && name !== 'sw.js') out.push(relative(root, p).split('\\').join('/'));
  }
  return out;
}

const files = walk(root).sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(root, f)));
const version = hash.digest('hex').slice(0, 12);
// Precache URLs are site-root paths, plus the site root itself.
const urls = ['/', ...files.map((f) => '/' + f)];

const sw = `// Generated by scripts/build-sw.mjs. Do not edit by hand.
const CACHE = "iggym-${version}";
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((n) => n.startsWith("iggym-") && n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  // Only same-origin requests. Outside services (AI providers, the Worker, analytics) always go to the network.
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).catch(() => {
        // Offline and not cached: show the 404 page for navigations, otherwise fail.
        if (req.mode === "navigate") return caches.match("/404.html", { ignoreSearch: true });
        return Response.error();
      });
    })
  );
});
`;
const target = join(root, 'sw.js');
if (process.argv.includes('--check')) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== sw) {
    console.error('sw.js is stale. Run: node scripts/build-sw.mjs');
    process.exit(1);
  }
  console.log('sw.js is up to date.');
} else {
  writeFileSync(target, sw, 'utf8');
  console.log(`wrote sw.js: cache iggym-${version}, ${urls.length} precached URLs`);
}
